### Отправка нового Бургера в базу данных FoodDash
POST http://localhost:8080/products
Content-Type: application/json

{
  "name": "Мега Бургер BBQ",
  "price": 490.00,
  "description": "Двойная котлета, бекон, карамелизированный лук и фирменный соус барбекю"
}


### Разбор кишок запроса: POST — приказ серверу «Создай!» [INDEX].
###Content-Type: application/json — предупреждаем Спринг, что по проводам летит именно текст в формате JSON [INDEX].
### Ниже через одну пустую строку лежит само тело (Body) нашего нового бургера [INDEX].