spring.application.name=fooddash-server
# 1. ??????? ?????? ?? ?????? (?????, ???? ? ??? ????)
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres

# 2. ????? ? ?????? ??????????? ?? ????? docker-???????
spring.datasource.username=postgres
spring.datasource.password=my_secret_pass

# 3. ???????-?????????? ??? ??????? ? PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# 4. ??????? ?????? ??? Hibernate (????????????? ????????? ???????!)
spring.jpa.hibernate.ddl-auto=update